# Generated by Django 6.0.7 on 2026-08-12 22:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, max_length=11, verbose_name='RUC')),
                ('document_type', models.CharField(blank=True, default='DNI', max_length=20)),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('full_name', models.CharField(max_length=255, verbose_name='nombre completo')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='cargo')),
                ('hired_on', models.DateField(blank=True, null=True, verbose_name='fecha de ingreso')),
                ('regimen', models.CharField(choices=[('afp', 'AFP'), ('onp', 'ONP'), ('sin_regimen', 'Todavía sin régimen')], default='sin_regimen', max_length=12, verbose_name='régimen pensionario')),
                ('afp', models.CharField(blank=True, choices=[('habitat', 'AFP Habitat'), ('integra', 'AFP Integra'), ('prima', 'Prima AFP'), ('profuturo', 'Profuturo AFP'), ('desconocida', 'Sin identificar')], max_length=12)),
                ('cuspp', models.CharField(blank=True, db_index=True, help_text='Lo pone la sincronización con AFPnet; no se escribe a mano.', max_length=20, verbose_name='CUSPP')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Nulo mientras no se sepa: no es lo mismo que cobrar cero.', max_digits=12, null=True, verbose_name='sueldo mensual')),
                ('salary_source', models.CharField(choices=[('manual', 'Registrado por la empresa'), ('afpnet', 'Última remuneración declarada en AFPnet')], default='manual', max_length=10)),
                ('salary_period', models.CharField(blank=True, help_text='Devengue del que se tomó el sueldo, cuando vino de AFPnet.', max_length=6)),
                ('salary_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='en planilla')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'colaborador',
                'verbose_name_plural': 'colaboradores',
                'ordering': ['full_name', 'document_number'],
                'indexes': [models.Index(fields=['taxpayer_id', 'is_active'], name='colaborador_taxpaye_469139_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('document_number', ''), _negated=True), fields=('taxpayer_id', 'document_number'), name='unique_colaborador_documento'), models.UniqueConstraint(condition=models.Q(('cuspp', ''), _negated=True), fields=('taxpayer_id', 'cuspp'), name='unique_colaborador_cuspp')],
            },
        ),
    ]
