# Generated by Django 6.0.7 on 2026-08-15 19:54

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, max_length=11, verbose_name='RUC')),
                ('numero', models.CharField(help_text='MEMO-2026-001. Se genera solo si el alta no lo trae.', max_length=30, verbose_name='n° de memorándum')),
                ('fecha_emision', models.DateField(verbose_name='fecha de emisión')),
                ('tipo', models.CharField(choices=[('llamada_atencion', 'Llamada de atención'), ('amonestacion', 'Amonestación escrita'), ('suspension', 'Suspensión'), ('felicitacion', 'Felicitación'), ('comunicacion', 'Comunicación interna'), ('otro', 'Otro')], default='llamada_atencion', max_length=20)),
                ('asunto', models.CharField(max_length=200, verbose_name='motivo / asunto')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción breve')),
                ('entregado', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('firmado', models.BooleanField(default=False, help_text='El colaborador firmó el cargo de recepción.', verbose_name='firmado de recepción')),
                ('archivo', models.CharField(blank=True, help_text='Ruta o enlace al documento firmado.', max_length=255, verbose_name='archivo / ruta')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorandums', to='colaboradores.colaborador')),
            ],
            options={
                'verbose_name': 'memorándum',
                'verbose_name_plural': 'memorándums',
                'ordering': ['-fecha_emision', '-created_at'],
                'indexes': [models.Index(fields=['taxpayer_id', 'colaborador'], name='colaborador_taxpaye_277acb_idx')],
                'constraints': [models.UniqueConstraint(fields=('taxpayer_id', 'numero'), name='unique_memorandum_numero')],
            },
        ),
    ]
