# Generated by Django 6.0.7 on 2026-08-15 20:26

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_memorandum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, max_length=11, verbose_name='RUC')),
                ('tipo', models.CharField(choices=[('indefinido', 'Indefinido'), ('sujeto_a_modalidad', 'Sujeto a modalidad'), ('tiempo_parcial', 'Tiempo parcial'), ('practicas', 'Prácticas / formativo'), ('otro', 'Otro')], default='sujeto_a_modalidad', max_length=20)),
                ('causa_objetiva', models.CharField(blank=True, help_text='Obligatoria en contratos sujetos a modalidad.', max_length=200, verbose_name='causa objetiva')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Vacía en contratos indefinidos.', null=True)),
                ('renovar', models.BooleanField(blank=True, null=True, verbose_name='¿renovar?')),
                ('nueva_fecha_fin', models.DateField(blank=True, help_text='Si se renueva: manda sobre fecha_fin para el vencimiento.', null=True, verbose_name='nueva fecha de fin')),
                ('fecha_comunicacion', models.DateField(blank=True, null=True, verbose_name='fecha de comunicación al trabajador')),
                ('archivo', models.FileField(blank=True, upload_to='contratos/%Y/%m/')),
                ('notas', models.TextField(blank=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='colaboradores.colaborador')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'ordering': ['-fecha_inicio', '-created_at'],
                'indexes': [models.Index(fields=['taxpayer_id', 'colaborador'], name='colaborador_taxpaye_8e1ad1_idx')],
            },
        ),
    ]
