# Generated by Django 6.0.7 on 2026-08-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
    ]
