# Generated by Django 6.0.7 on 2026-08-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_colaborador_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Texto, nunca número: conserva los ceros a la izquierda.', max_length=30, verbose_name='cuenta bancaria'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='bank_cci',
            field=models.CharField(blank=True, max_length=30, verbose_name='CCI'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='bank_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='banco'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='has_eps',
            field=models.BooleanField(default=False, help_text='Cambia la tasa del aporte de salud del empleador.', verbose_name='afiliado a EPS'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='pension_commission_type',
            field=models.CharField(blank=True, choices=[('flow', 'Comisión sobre flujo'), ('mixed', 'Comisión mixta')], help_text='Dato del afiliado, no de la AFP. Solo con régimen AFP.', max_length=10, verbose_name='tipo de comisión AFP'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='receives_family_allowance',
            field=models.BooleanField(default=False, verbose_name='percibe asignación familiar'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='subject_to_sctr',
            field=models.BooleanField(default=False, verbose_name='realiza trabajo de riesgo (SCTR)'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='terminated_on',
            field=models.DateField(blank=True, help_text='Permite prorratear el mes de salida y calcular truncos; no es lo mismo que el vencimiento del contrato.', null=True, verbose_name='fecha de cese'),
        ),
    ]
