# Generated by Django 6.0.7 on 2026-08-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0005_colaborador_bank_account_number_colaborador_bank_cci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='expense_classification',
            field=models.CharField(choices=[('cost_of_sales', 'Costo de venta'), ('administrative', 'Gastos administrativos'), ('selling', 'Gastos de ventas')], default='administrative', help_text='A qué renglón del Estado de Resultados va su costo laboral.', max_length=15, verbose_name='clasificación del gasto'),
        ),
    ]
