# Generated by Django 6.0.7 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0006_colaborador_expense_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memorandum",
            name="archivo",
            field=models.FileField(
                blank=True,
                help_text="Documento firmado o sustento del memorándum.",
                upload_to="memorandums/%Y/%m/",
            ),
        ),
    ]
