# Generated by Django 6.0.7 on 2026-08-21

from pathlib import PurePosixPath

import core.models
import django.db.models.deletion
from django.db import migrations, models


def completar_metadatos(apps, schema_editor):
    Contrato = apps.get_model("colaboradores", "Contrato")
    for contrato in Contrato.objects.exclude(archivo="").iterator():
        ruta = str(contrato.archivo).replace("\\", "/")
        contrato.archivo_nombre_original = PurePosixPath(ruta).name
        contrato.archivo_cargado_en = contrato.updated_at
        contrato.save(
            update_fields=["archivo_nombre_original", "archivo_cargado_en"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0007_alter_memorandum_archivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="archivo_cargado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contrato",
            name="archivo_nombre_original",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="ContratoArchivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.models.default_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "taxpayer_id",
                    models.CharField(db_index=True, max_length=11, verbose_name="RUC"),
                ),
                ("archivo", models.FileField(upload_to="contratos/%Y/%m/")),
                ("nombre_original", models.CharField(max_length=255)),
                ("cargado_en", models.DateTimeField()),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versiones_archivo",
                        to="colaboradores.contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "versión de archivo de contrato",
                "verbose_name_plural": "versiones de archivos de contratos",
                "ordering": ["-cargado_en", "-created_at"],
            },
        ),
        migrations.RunPython(completar_metadatos, migrations.RunPython.noop),
    ]
