# Generated by Django 6.0.7 on 2026-08-01 01:15

import core.models
import django.db.models.deletion
import suppliers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(max_length=11, unique=True, validators=[suppliers.validators.validate_ruc], verbose_name='RUC')),
                ('alias', models.CharField(blank=True, help_text='Internal name for this supplier. Falls back to the SUNAT name.', max_length=120)),
                ('business_name', models.CharField(blank=True, help_text='Razón social, as reported by SUNAT.', max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('taxpayer_type', models.CharField(blank=True, max_length=120)),
                ('fiscal_address', models.TextField(blank=True)),
                ('economic_activities', models.TextField(blank=True)),
                ('registered_on', models.DateField(blank=True, null=True)),
                ('started_activities_on', models.DateField(blank=True, null=True)),
                ('is_tracked', models.BooleanField(default=True, help_text='Untracked suppliers are skipped by the daily check.')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=60)),
                ('condition', models.CharField(blank=True, db_index=True, max_length=60)),
                ('has_issue', models.BooleanField(db_index=True, default=False)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, help_text='When the status or condition last changed.', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Why the most recent check failed, if it did.')),
            ],
            options={
                'ordering': ['alias', 'business_name', 'ruc'],
                'indexes': [models.Index(fields=['is_tracked', 'has_issue'], name='suppliers_s_is_trac_d30728_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierCheck',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_on', models.DateField(db_index=True)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('condition', models.CharField(blank=True, max_length=60)),
                ('has_issue', models.BooleanField(db_index=True, default=False)),
                ('changed', models.BooleanField(db_index=True, default=False)),
                ('previous_status', models.CharField(blank=True, max_length=60)),
                ('previous_condition', models.CharField(blank=True, max_length=60)),
                ('succeeded', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-checked_on', '-created_at'],
                'indexes': [models.Index(fields=['supplier', '-checked_on'], name='suppliers_s_supplie_004cba_idx')],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'checked_on'), name='unique_supplier_check_per_day')],
            },
        ),
    ]
