# Generated by Django 6.0.7 on 2026-08-08 13:58

import suppliers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='account_ruc',
            field=models.CharField(db_index=True, default='', help_text='Empresa dueña de esta ficha de proveedor.', max_length=11, verbose_name='RUC de la empresa'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ruc',
            field=models.CharField(db_index=True, max_length=11, validators=[suppliers.validators.validate_ruc], verbose_name='RUC'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('account_ruc', 'ruc'), name='unique_supplier_per_account'),
        ),
    ]
