# Generated by Django 6.0.7 on 2026-08-27 22:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_account_ruc_alter_supplier_ruc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SujetoSinCapacidadOperativa',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(max_length=11, unique=True, verbose_name='RUC')),
                ('razon_social', models.CharField(blank=True, max_length=255)),
                ('domicilio_fiscal', models.TextField(blank=True)),
                ('resolucion', models.CharField(blank=True, max_length=160)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('fecha_firme', models.DateField(blank=True, help_text='Cuándo la resolución quedó firme.', null=True)),
                ('representante_documento', models.CharField(blank=True, max_length=20)),
                ('representante_nombre', models.CharField(blank=True, max_length=255)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('vigente', models.BooleanField(db_index=True, default=True)),
                ('visto_el', models.DateField(help_text='Última descarga del padrón en la que apareció.')),
            ],
            options={
                'verbose_name': 'sujeto sin capacidad operativa',
                'verbose_name_plural': 'sujetos sin capacidad operativa',
                'ordering': ['-fecha_publicacion', 'ruc'],
            },
        ),
    ]
