# Generated by Django 6.0.7 on 2026-08-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_sujetosincapacidadoperativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujetosincapacidadoperativa',
            name='representante_documento',
            field=models.TextField(blank=True),
        ),
    ]
