# Generated by Django 6.0.7 on 2026-08-23 14:48

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono / WhatsApp')),
                ('ruc', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El RUC tiene 11 dígitos.')], verbose_name='RUC')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='empresa')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('source', models.CharField(default='landing', max_length=60, verbose_name='origen')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='contactado el')),
                ('notes', models.TextField(blank=True, verbose_name='notas internas')),
            ],
            options={
                'verbose_name': 'interesado',
                'verbose_name_plural': 'interesados',
                'ordering': ['-created_at'],
            },
        ),
    ]
