# Generated by Django 6.0.7 on 2026-08-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_planes_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('one_off', 'Pago único'), ('recurring_setup', 'Alta de suscripción'), ('recurring_charge', 'Cobro recurrente')], default='one_off', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='recurring',
            field=models.BooleanField(default=True, verbose_name='cobro recurrente'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='renovación automática'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gateway',
            field=models.CharField(blank=True, max_length=20, verbose_name='pasarela'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gateway_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='estado en la pasarela'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gateway_subscription_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='id de suscripción en la pasarela'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_charge_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='próximo cobro'),
        ),
    ]
