# Generated by Django 6.0.7 on 2026-08-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_recurrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='aviso de fin de prueba enviado'),
        ),
    ]
