# Generated by Django 6.0.7 on 2026-08-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_beat_fin_de_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='included_company_seats',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='empresas incluidas'),
        ),
    ]
