# Generated by Django 6.0.7 on 2026-08-24 14:25

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organization_manual_sync_daily_limit'),
        ('billing', '0006_plan_included_company_seats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageCharge',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('extra_manual_sync', 'Sincronización manual adicional')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Por cobrar'), ('settled', 'Cobrado'), ('waived', 'Exonerado')], default='pending', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_charges_made', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_charges', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'cargo por uso',
                'verbose_name_plural': 'cargos por uso',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='billing_usa_organiz_5cdf20_idx')],
            },
        ),
    ]
