# Generated by Django 6.0.7 on 2026-08-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_usagecharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paused_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pausada en la pasarela hasta'),
        ),
    ]
