# Generated by Django 6.0.7 on 2026-08-26 04:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_beat_reanudar_pausadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='extra_company_seat_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=10, verbose_name='precio por empresa adicional (mes)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='extra_member_seat_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=10, verbose_name='precio por persona adicional (mes)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='included_member_seats',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='personas incluidas por empresa'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='extra_company_seats',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='empresas adicionales'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='extra_member_seats',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='personas adicionales'),
        ),
    ]
