# Generated by Django 6.0.7 on 2026-08-01 00:01

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, help_text='Taxpayer identification number the message belongs to.', max_length=11, verbose_name='RUC')),
                ('message_code', models.BigIntegerField(help_text="SUNAT's codMensaje.")),
                ('message_type', models.SmallIntegerField(choices=[(1, 'Message'), (2, 'Notification')])),
                ('subject', models.TextField(blank=True)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('office_code', models.CharField(blank=True, max_length=10)),
                ('label_code', models.CharField(blank=True, max_length=10)),
                ('sent_on', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text="SUNAT's fecLectura. Only known once the detail has been fetched.", null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Derived from read_at; see Attachment sync notes.')),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('attachment_count', models.PositiveIntegerField(default=0)),
                ('status_code', models.SmallIntegerField(blank=True, help_text="SUNAT's indEstado, stored verbatim; its semantics are undocumented.", null=True)),
                ('list_payload', models.JSONField(blank=True, default=dict)),
                ('detail_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-message_code'],
                'indexes': [models.Index(fields=['taxpayer_id', 'message_type'], name='sunat_mailb_taxpaye_326669_idx'), models.Index(fields=['-published_at'], name='sunat_mailb_publish_dde644_idx')],
                'constraints': [models.UniqueConstraint(fields=('taxpayer_id', 'message_code', 'message_type'), name='unique_message_per_taxpayer')],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_code', models.BigIntegerField(blank=True, help_text="SUNAT's codArchivo.", null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('size_display', models.CharField(blank=True, max_length=50)),
                ('external_id', models.BigIntegerField(blank=True, help_text="SUNAT's numId.", null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sunat_mailbox.message')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message', 'file_code'], name='sunat_mailb_message_9af8ef_idx')],
            },
        ),
    ]
