# Generated by Django 6.0.7 on 2026-08-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat_mailbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='checksum',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 of the downloaded bytes; identical files share a checksum.', max_length=64),
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attachment',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='extraction_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Not downloaded yet'), ('extracted', 'Text extracted'), ('empty', 'PDF has no text layer (needs OCR)'), ('unsupported', 'Not a PDF'), ('failed', 'Download or extraction failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='attachment',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='text_content',
            field=models.TextField(blank=True),
        ),
    ]
