# Generated by Django 6.0.7 on 2026-08-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat_mailbox', '0002_attachment_checksum_attachment_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the message was opened in this app. Independent from read_at: reviewing here does not mark the message as read in SUNAT SOL.', null=True),
        ),
    ]
