# Generated by Django 6.0.7 on 2026-08-01 02:56

import core.models
import suppliers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemypeCheck',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(db_index=True, max_length=11, validators=[suppliers.validators.validate_ruc], verbose_name='RUC')),
                ('checked_on', models.DateField(db_index=True)),
                ('is_registered', models.BooleanField(db_index=True, default=False)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('condition', models.CharField(blank=True, help_text="REMYPE's CONDICION, e.g. 'ACREDITADO COMO MICRO EMPRESA'.", max_length=120)),
                ('situation', models.CharField(blank=True, help_text='SITUACIONEMPRESA.', max_length=120)),
                ('mype_category', models.CharField(blank=True, help_text='FLG_MYPE.', max_length=120)),
                ('file_number', models.CharField(blank=True, help_text='NUMEROFICHASOLICITUD.', max_length=60)),
                ('registry_code', models.BigIntegerField(blank=True, help_text='N_CODREG.', null=True)),
                ('requested_on', models.DateField(blank=True, null=True)),
                ('accredited_on', models.DateField(blank=True, null=True)),
                ('deregistered_on', models.DateField(blank=True, null=True)),
                ('changed', models.BooleanField(db_index=True, default=False, help_text='The registry standing differs from the previous check.')),
                ('previous_condition', models.CharField(blank=True, max_length=120)),
                ('succeeded', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, help_text="REMYPE's message, or the error.")),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'REMYPE check',
                'verbose_name_plural': 'REMYPE checks',
                'ordering': ['-checked_on', 'ruc'],
                'indexes': [models.Index(fields=['ruc', '-checked_on'], name='remype_remy_ruc_18722e_idx')],
                'constraints': [models.UniqueConstraint(fields=('ruc', 'checked_on'), name='unique_remype_check_per_day')],
            },
        ),
    ]
