# Generated by Django 6.0.7 on 2026-08-28 15:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaDeclaraciones',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('periodo_desde', models.CharField(max_length=6)),
                ('periodo_hasta', models.CharField(max_length=6)),
                ('filas', models.PositiveIntegerField(default=0)),
                ('nuevas', models.PositiveIntegerField(default=0)),
                ('succeeded', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'consulta de declaraciones',
                'verbose_name_plural': 'consultas de declaraciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeclaracionPresentada',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('periodo', models.CharField(db_index=True, help_text='AAAAMM. SUNAT usa AAAA13 para la declaración anual.', max_length=6)),
                ('formulario', models.CharField(db_index=True, max_length=4)),
                ('descripcion', models.CharField(blank=True, max_length=120)),
                ('nro_orden', models.CharField(max_length=20)),
                ('fecha_presentacion', models.DateField(blank=True, db_index=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('banco', models.CharField(blank=True, max_length=120)),
                ('importe_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tipo_formulario', models.CharField(blank=True, max_length=4)),
                ('tipo_formulario_desc', models.CharField(blank=True, max_length=80)),
                ('medio_presentacion', models.CharField(blank=True, max_length=60)),
                ('nro_orden_original', models.CharField(blank=True, max_length=20)),
                ('nro_operacion_sunat', models.CharField(blank=True, max_length=30)),
                ('nro_operacion_banco', models.CharField(blank=True, max_length=40)),
                ('es_boleta', models.BooleanField(default=False)),
                ('rectificatoria', models.BooleanField(default=False)),
                ('casillas', models.JSONField(blank=True, default=dict)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('visto_el', models.DateField(help_text='Última consulta en la que apareció.')),
            ],
            options={
                'verbose_name': 'declaración presentada',
                'verbose_name_plural': 'declaraciones presentadas',
                'ordering': ['-periodo', '-fecha_presentacion', 'formulario'],
                'indexes': [models.Index(fields=['account_ruc', 'periodo', 'formulario'], name='sunat_decla_account_c26308_idx')],
                'constraints': [models.UniqueConstraint(fields=('account_ruc', 'nro_orden'), name='unique_declaracion_orden')],
            },
        ),
    ]
