# Generated by Django 6.0.7 on 2026-08-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat_declaraciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionpresentada',
            name='constancia',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
