# Generated by Django 6.0.7 on 2026-08-28 16:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat_declaraciones', '0002_constancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionAnual',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('ejercicio', models.CharField(db_index=True, max_length=4)),
                ('formulario', models.CharField(default='0710', max_length=4)),
                ('nro_orden', models.CharField(max_length=20)),
                ('id_presentacion', models.CharField(blank=True, max_length=40)),
                ('tipo_declaracion', models.CharField(blank=True, max_length=40)),
                ('rectificatoria', models.BooleanField(default=False)),
                ('fecha_presentacion', models.DateTimeField(blank=True, null=True)),
                ('medio_pago', models.CharField(blank=True, max_length=80)),
                ('importe_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('casillas', models.JSONField(blank=True, default=dict)),
                ('tributos', models.JSONField(blank=True, default=list)),
                ('anexos', models.JSONField(blank=True, default=dict)),
                ('archivo', models.FileField(blank=True, upload_to='renta_anual/%Y/')),
                ('raw_resumen', models.JSONField(blank=True, default=dict)),
                ('raw_detallado', models.JSONField(blank=True, default=dict)),
                ('visto_el', models.DateField()),
            ],
            options={
                'verbose_name': 'declaración anual de renta',
                'verbose_name_plural': 'declaraciones anuales de renta',
                'ordering': ['-ejercicio', '-fecha_presentacion'],
                'constraints': [models.UniqueConstraint(fields=('account_ruc', 'nro_orden'), name='unique_declaracion_anual_orden')],
            },
        ),
    ]
