# Generated by Django 6.0.7 on 2026-08-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='kind',
            field=models.CharField(choices=[('inicial', 'Primera carga'), ('diaria', 'Diaria'), ('mensual', 'Mensual'), ('manual', 'A pedido')], default='inicial', help_text='Qué disparó el trabajo; determina qué fuentes se consultan.', max_length=10),
        ),
    ]
