# Generated by Django 6.0.7 on 2026-08-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_tenant_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncjob',
            name='status',
            field=models.CharField(choices=[('en_cola', 'En cola'), ('ejecutando', 'Ejecutando'), ('completo', 'Completo'), ('parcial', 'Completo con fallas'), ('fallido', 'Fallido'), ('cancelado', 'Cancelada')], default='en_cola', max_length=12),
        ),
    ]
