# Generated by Django 6.0.7 on 2026-08-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=6)),
                ('severity', models.CharField(choices=[('ROJO', 'Rojo'), ('AMBAR', 'Ámbar'), ('INFO', 'Info')], max_length=6)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.JSONField(default=dict)),
                ('amount_at_risk', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('due_date', models.DateField(null=True)),
                ('status', models.CharField(default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['status', 'severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inconsistency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('RVIE', 'RVIE (sales)'), ('RCE', 'RCE (purchases)')], max_length=4)),
                ('tax_period', models.CharField(db_index=True, max_length=6)),
                ('kind', models.CharField(max_length=60)),
                ('detail', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'inconsistencies',
                'ordering': ['-tax_period'],
            },
        ),
        migrations.CreateModel(
            name='RawArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=80)),
                ('params', models.JSONField(default=dict)),
                ('local_path', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SscoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('detail', models.JSONField(default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SSCO entry',
                'verbose_name_plural': 'SSCO entries',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('registry_status', models.CharField(blank=True, max_length=30)),
                ('registry_condition', models.CharField(blank=True, max_length=30)),
                ('in_ssco', models.BooleanField(default=False)),
                ('total_purchased', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igv_at_risk', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['-total_purchased'],
            },
        ),
        migrations.CreateModel(
            name='BoxSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('RVIE', 'RVIE (sales)'), ('RCE', 'RCE (purchases)')], max_length=4)),
                ('tax_period', models.CharField(db_index=True, max_length=6)),
                ('box', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('captured_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-tax_period', 'box'],
                'unique_together': {('book', 'tax_period', 'box')},
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('RVIE', 'RVIE (sales)'), ('RCE', 'RCE (purchases)')], max_length=4)),
                ('tax_period', models.CharField(max_length=6)),
                ('status', models.CharField(default='?', help_text="SUNAT's desEstado for the period, stored verbatim.", max_length=60)),
                ('status_code', models.CharField(blank=True, max_length=4)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-tax_period', 'book'],
                'unique_together': {('book', 'tax_period')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_period', models.CharField(db_index=True, max_length=6)),
                ('doc_type', models.CharField(max_length=2)),
                ('series', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=12)),
                ('issue_date', models.DateField(null=True)),
                ('supplier_ruc', models.CharField(blank=True, max_length=15)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('car_sunat', models.CharField(blank=True, max_length=35)),
                ('raw_extra', models.JSONField(default=dict)),
                ('recognized', models.BooleanField(help_text='None = not reviewed yet (rule R6).', null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issue_date'],
                'unique_together': {('doc_type', 'series', 'number')},
            },
        ),
        migrations.CreateModel(
            name='SalesDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_period', models.CharField(db_index=True, max_length=6)),
                ('doc_type', models.CharField(max_length=2)),
                ('series', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=12)),
                ('issue_date', models.DateField(null=True)),
                ('customer_ruc', models.CharField(blank=True, max_length=15)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('car_sunat', models.CharField(blank=True, max_length=35)),
                ('raw_extra', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-issue_date'],
                'unique_together': {('doc_type', 'series', 'number')},
            },
        ),
    ]
