# Generated by Django 6.0.7 on 2026-08-05 16:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicInvoice',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, help_text='RUC of the logged-in SOL account this record belongs to.', max_length=11, verbose_name='RUC de la cuenta')),
                ('direction', models.CharField(choices=[('emitida', 'Emitida'), ('recibida', 'Recibida')], db_index=True, max_length=10)),
                ('document_class', models.CharField(choices=[('factura', 'Factura'), ('nota_credito', 'Nota de crédito'), ('nota_debito', 'Nota de débito')], db_index=True, max_length=15)),
                ('document_type', models.CharField(help_text='tipoCPE.', max_length=3)),
                ('cpe_code', models.CharField(blank=True, help_text='codCpe (01/07/08).', max_length=2)),
                ('download_code', models.CharField(blank=True, help_text='codFactura.', max_length=3)),
                ('tipo_consulta', models.CharField(blank=True, help_text='Last tipoConsulta that surfaced this row.', max_length=2)),
                ('issuer_ruc', models.CharField(db_index=True, help_text='nroRucEmisor.', max_length=15)),
                ('issuer_name', models.CharField(blank=True, max_length=200)),
                ('receiver_doc_type', models.CharField(blank=True, max_length=2)),
                ('receiver_ruc', models.CharField(blank=True, db_index=True, max_length=15)),
                ('receiver_name', models.CharField(blank=True, max_length=200)),
                ('series', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=12)),
                ('full_number', models.CharField(blank=True, max_length=30)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('period', models.CharField(db_index=True, max_length=6)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('currency_symbol', models.CharField(blank=True, max_length=5)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('status', models.CharField(blank=True, help_text='estadoDesc.', max_length=40)),
                ('is_cancelled', models.BooleanField(default=False, help_text='ind_anulado.')),
                ('is_rejected', models.BooleanField(default=False)),
                ('reject_date', models.CharField(blank=True, max_length=20)),
                ('references_document', models.CharField(blank=True, db_index=True, help_text='Original comprobante a NC/ND is issued against.', max_length=60)),
                ('xml_id', models.CharField(blank=True, max_length=20)),
                ('can_download', models.BooleanField(default=False)),
                ('xml_content', models.TextField(blank=True, help_text='Signed UBL XML text.')),
                ('xml_filename', models.CharField(blank=True, max_length=120)),
                ('xml_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('xml_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-issue_date', '-number'],
                'indexes': [models.Index(fields=['account_ruc', 'direction', 'period'], name='sunat_cpe_e_account_3f91ae_idx'), models.Index(fields=['-issue_date'], name='sunat_cpe_e_issue_d_6c313c_idx')],
                'constraints': [models.UniqueConstraint(fields=('account_ruc', 'issuer_ruc', 'document_type', 'series', 'number'), name='unique_cpe_per_account')],
            },
        ),
    ]
