# Generated by Django 6.0.7 on 2026-09-04 13:06

import sunat_cpe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat_cpe', '0003_fix_html_entity_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicinvoice',
            name='xml_file',
            field=models.FileField(blank=True, max_length=255, upload_to=sunat_cpe.models.xml_file_path, verbose_name='archivo XML'),
        ),
    ]
