# Generated by Django 6.0.7 on 2026-08-08 13:30

import accounts.models
import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El RUC debe tener 11 dígitos.')], verbose_name='RUC')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='razón social')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='nombre comercial')),
            ],
            options={
                'ordering': ['name', 'ruc'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('first_name', models.CharField(blank=True, max_length=80, verbose_name='nombres')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='apellidos')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['email'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SunatCredential',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sol_username', models.CharField(max_length=60, verbose_name='usuario SOL')),
                ('encrypted_password', models.TextField(verbose_name='clave SOL cifrada')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente de validar'), ('conectada', 'Conectada'), ('invalida', 'Credenciales rechazadas'), ('desconectada', 'Desconectada')], default='pendiente', max_length=15)),
                ('uses_primary_user', models.BooleanField(default=False, help_text='El contribuyente aceptó entregar su usuario SOL principal.')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunat_connections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sunat_credential', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'credencial SUNAT',
                'verbose_name_plural': 'credenciales SUNAT',
            },
        ),
        migrations.CreateModel(
            name='OneTimeToken',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('email_verification', 'Verificación de correo'), ('password_reset', 'Recuperación de contraseña')], max_length=25)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose'], name='accounts_on_user_id_d58e9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Titular'), ('accountant', 'Contador'), ('viewer', 'Solo lectura')], default='owner', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.organization')),
            ],
            options={
                'ordering': ['organization__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='unique_membership')],
            },
        ),
    ]
