# Generated by Django 6.0.7 on 2026-08-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tax_regime_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_regime_source',
            field=models.CharField(blank=True, choices=[('sunat', 'Leído de la Ficha RUC (SOL)'), ('usuario', 'Declarado por el usuario')], max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tax_regime',
            field=models.CharField(blank=True, choices=[('RUS', 'Nuevo RUS'), ('RER', 'Régimen Especial'), ('RMT', 'MYPE Tributario'), ('RG', 'Régimen General')], help_text='Vacío mientras no se haya leído de SUNAT ni declarado.', max_length=3, verbose_name='régimen tributario'),
        ),
    ]
