# Generated by Django 6.0.7 on 2026-08-23 19:42

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_regimen_sunat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunatAuthorization',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sol_username', models.CharField(blank=True, max_length=60)),
                ('version', models.CharField(max_length=10)),
                ('text_sha256', models.CharField(max_length=64)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunat_authorizations', to='accounts.organization')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunat_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'autorización SUNAT',
                'verbose_name_plural': 'autorizaciones SUNAT',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
