# Generated by Django 6.0.7 on 2026-08-24 05:15

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_membership_invited_by_user_extra_company_seats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offering', models.CharField(blank=True, choices=[('products', 'Productos'), ('services', 'Servicios'), ('food', 'Comida o bebidas'), ('mixed', 'Un poco de todo'), ('unsure', 'No estoy seguro')], max_length=15)),
                ('sector', models.CharField(blank=True, choices=[('commerce', 'Comercio'), ('services', 'Servicios'), ('manufacturing', 'Manufactura'), ('food', 'Alimentos'), ('construction', 'Construcción'), ('other', 'Otro')], max_length=15)),
                ('primary_goal', models.CharField(blank=True, choices=[('order_numbers', 'Ordenar mis números'), ('tax_ready', 'Prepararme para impuestos'), ('cashflow', 'No quedarme sin caja'), ('growth', 'Crecer con más claridad'), ('profitability', 'Saber si vendo con ganancia')], max_length=15)),
                ('business_age', models.CharField(blank=True, choices=[('starting', 'Estoy empezando'), ('selling', 'Ya estoy vendiendo'), ('established', 'Empresa establecida')], max_length=15)),
                ('people_count', models.PositiveSmallIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'perfil del negocio',
                'verbose_name_plural': 'perfiles del negocio',
            },
        ),
    ]
