# Generated by Django 6.0.7 on 2026-08-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_businessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='manual_sync_daily_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='límite de sincronizaciones manuales al día'),
        ),
    ]
