# Generated by Django 6.0.7 on 2026-08-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organization_manual_sync_daily_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='has_premises',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='atiende en local físico'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='sells_online',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='vende por internet'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='sells_to_consumers',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='vende al consumidor final'),
        ),
    ]
