# Generated by Django 6.0.7 on 2026-09-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_businessprofile_offerings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimetoken',
            name='purpose',
            field=models.CharField(choices=[('email_verification', 'Verificación de correo'), ('password_reset', 'Recuperación de contraseña'), ('admin_otp', 'Código de acceso al admin')], max_length=25),
        ),
    ]
