# Generated by Django 6.0.7 on 2026-08-23 20:00

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sunat_cpe', '0003_fix_html_entity_amounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMovement',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('date', models.DateField()),
                ('period', models.CharField(db_index=True, max_length=6)),
                ('bank', models.CharField(blank=True, max_length=60)),
                ('bank_account', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('kind', models.CharField(choices=[('credit', 'Abono'), ('debit', 'Cargo')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('operation_number', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(default='import', max_length=20)),
                ('category', models.CharField(choices=[('invoice_collection', 'Cobro de factura'), ('supplier_payment', 'Pago a proveedor'), ('own_transfer', 'Transferencia entre cuentas propias'), ('loan', 'Préstamo'), ('capital', 'Aporte de capital'), ('refund', 'Devolución'), ('reimbursement', 'Reembolso'), ('tax_payment', 'Pago de tributos'), ('payroll', 'Pago de planilla'), ('other', 'Otros'), ('unidentified', 'No identificado')], default='unidentified', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('classified_by', models.CharField(blank=True, choices=[('rules', 'Reglas'), ('ai', 'IA (auxiliar)'), ('user', 'Usuario')], max_length=10)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['account_ruc', 'period', 'kind'], name='reconciliat_account_9037a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeclaredSummary',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('period', models.CharField(db_index=True, max_length=6)),
                ('sales_base', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sales_igv', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('purchases_base', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('purchases_igv', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('igv_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('income_tax_declared', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_declared', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('filed_at', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('sire', 'Reporte de casillas SIRE'), ('manual', 'Ingresado a mano'), ('import', 'Importado')], default='manual', max_length=10)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('account_ruc', 'period')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceSettlement',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('status', models.CharField(choices=[('unpaid', 'Sin pago'), ('partial', 'Pago parcial'), ('paid', 'Pagada'), ('overpaid', 'Pago excedente'), ('undetermined', 'No determinado')], default='unpaid', max_length=15)),
                ('invoice_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('billing_period', models.CharField(db_index=True, max_length=6)),
                ('collection_period', models.CharField(blank=True, max_length=6)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='sunat_cpe.electronicinvoice')),
            ],
            options={
                'ordering': ['-billing_period'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('period', models.CharField(db_index=True, max_length=6)),
                ('status', models.CharField(choices=[('running', 'Ejecutando'), ('done', 'Terminado'), ('failed', 'Falló')], default='running', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('findings_count', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account_ruc', 'period'], name='reconciliat_account_3e55f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentReconciliation',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('period', models.CharField(db_index=True, max_length=6)),
                ('direction', models.CharField(choices=[('sales', 'Ventas'), ('purchases', 'Compras')], max_length=10)),
                ('doc_key', models.CharField(db_index=True, max_length=40)),
                ('counterparty_ruc', models.CharField(blank=True, max_length=15)),
                ('counterparty_name', models.CharField(blank=True, max_length=200)),
                ('sire_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('matched', 'Coincide'), ('cpe_only', 'CPE sin registro SIRE'), ('sire_only', 'Registro SIRE sin CPE'), ('amount_mismatch', 'Diferencia de monto'), ('igv_mismatch', 'Diferencia de IGV'), ('date_mismatch', 'Diferencia de fecha'), ('party_mismatch', 'Diferencia de contraparte'), ('cancelled_mismatch', 'Anulado registrado distinto')], max_length=20)),
                ('level', models.CharField(choices=[('ok', 'OK'), ('warning', 'Advertencia'), ('review', 'Revisar'), ('critical', 'Crítico')], max_length=10)),
                ('cpe_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sire_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cpe_igv', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sire_igv', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('differences', models.JSONField(blank=True, default=dict)),
                ('cpe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to='sunat_cpe.electronicinvoice')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reconciliation.reconciliationrun')),
            ],
            options={
                'ordering': ['level', 'doc_key'],
                'indexes': [models.Index(fields=['account_ruc', 'period', 'direction'], name='reconciliat_account_6c180f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsistencyScore',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('period', models.CharField(db_index=True, max_length=6)),
                ('score', models.PositiveSmallIntegerField()),
                ('breakdown', models.JSONField(blank=True, default=list)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reconciliation.reconciliationrun')),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('account_ruc', 'period')},
            },
        ),
        migrations.CreateModel(
            name='SettlementLine',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('confidence', models.FloatField(default=0)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('matched_by', models.CharField(default='rules', max_length=10)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_lines', to='reconciliation.bankmovement')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reconciliation.invoicesettlement')),
            ],
            options={
                'unique_together': {('settlement', 'movement')},
            },
        ),
    ]
