# Generated by Django 6.0.7 on 2026-08-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationrun',
            name='ai_explanation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
