# Generated by Django 6.0.7 on 2026-08-23 20:59

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_ai_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('file', models.FileField(upload_to='statements/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('bank', models.CharField(blank=True, max_length=60)),
                ('bank_account', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('status', models.CharField(choices=[('uploaded', 'Subido'), ('locked', 'Protegido (falta contraseña)'), ('parsed', 'Procesado'), ('failed', 'Falló')], default='uploaded', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('movement_count', models.PositiveIntegerField(default=0)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bankmovement',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='reconciliation.bankstatement'),
        ),
    ]
