# Generated by Django 6.0.7 on 2026-09-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0004_bankmovement_classified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettlement',
            name='credit_notes_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='invoicesettlement',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Sin pago'), ('partial', 'Pago parcial'), ('paid', 'Pagada'), ('credited', 'Cubierta por nota de crédito'), ('overpaid', 'Pago excedente'), ('undetermined', 'No determinado')], default='unpaid', max_length=15),
        ),
    ]
