# Generated by Django 6.0.7 on 2026-08-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_purchase_returns_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='source',
            field=models.CharField(choices=[('sunat_sales', 'Venta SUNAT'), ('sunat_purchases', 'Compra SUNAT'), ('manual_sale', 'Venta manual'), ('manual_purchase', 'Compra manual'), ('payroll', 'Planilla'), ('fee_receipt', 'Recibo por honorarios'), ('adjustment', 'Ajuste')], max_length=20),
        ),
    ]
