# Generated by Django 6.0.7 on 2026-09-04 14:08

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentExport',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11, verbose_name='RUC de la empresa')),
                ('source', models.CharField(choices=[('cpe', 'Facturas y notas'), ('rhe', 'Recibos por honorarios')], max_length=5)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, help_text='El filtro, en palabras.', max_length=200)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('code_hash', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('zip_bytes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(help_text='Quien pidió la descarga; se conserva el registro aunque se borre la cuenta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'descarga de comprobantes',
                'verbose_name_plural': 'descargas de comprobantes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account_ruc', '-created_at'], name='documents_d_account_155ab4_idx')],
            },
        ),
    ]
