# Generated by Django 6.0.7 on 2026-08-01 04:56

import core.models
import suppliers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SunafilItem',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, max_length=11, validators=[suppliers.validators.validate_ruc], verbose_name='RUC')),
                ('kind', models.CharField(choices=[('orientation', 'Sunafil te Orienta'), ('requirement', 'Acciones previas / requerimientos'), ('inspection_notice', 'Notificación de fiscalización'), ('collection_notice', 'Notificación de cobranza')], db_index=True, max_length=20)),
                ('external_key', models.CharField(help_text='Hash of the columns that identify this row across runs.', max_length=32)),
                ('subject', models.TextField(blank=True, help_text='Asunto, or the requirement type.')),
                ('category', models.CharField(blank=True, max_length=120)),
                ('record_number', models.CharField(blank=True, db_index=True, help_text='Registro / orden de inspección / expediente sancionador.', max_length=120)),
                ('office', models.CharField(blank=True, help_text='Intendencia.', max_length=120)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('deposited_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notified_on', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, help_text='Fecha límite de presentación.', null=True)),
                ('deadline_days', models.PositiveIntegerField(blank=True, null=True)),
                ('row', models.JSONField(blank=True, default=dict)),
                ('detail_text', models.TextField(blank=True)),
                ('detail_html', models.TextField(blank=True)),
                ('detail_links', models.JSONField(blank=True, default=list)),
                ('detail_images', models.JSONField(blank=True, default=list)),
                ('detail_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_on', models.DateField(db_index=True)),
                ('last_seen_on', models.DateField(db_index=True)),
            ],
            options={
                'ordering': ['-deposited_at', '-first_seen_on'],
                'indexes': [models.Index(fields=['taxpayer_id', 'kind', '-deposited_at'], name='sunafil_sun_taxpaye_c479dd_idx'), models.Index(fields=['kind', 'is_read'], name='sunafil_sun_kind_290559_idx')],
                'constraints': [models.UniqueConstraint(fields=('taxpayer_id', 'kind', 'external_key'), name='unique_sunafil_item')],
            },
        ),
    ]
