"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str = "") -> list[str]:
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


# Llave Fernet con la que se cifra la clave SOL de cada empresa. Vive en el
# entorno, nunca en la base ni en el repositorio; ver accounts/services/crypto.py.
FIELD_ENCRYPTION_KEY = os.getenv("FIELD_ENCRYPTION_KEY", "")

# SUNAT SIRE APIs (prototipo sensor_sunat). Aquí solo viven las constantes de
# los endpoints: las credenciales son de cada empresa (accounts.SunatCredential
# guarda las SOL; el client_id/secret del SIRE se genera por RUC en el menú SOL
# y todavía no se guarda por empresa, así que el prototipo queda sin credencial
# hasta que eso exista — nunca vuelve a leerlas del entorno).
SUNAT = {
    "RUC": "",
    "SOL_USER": "",
    "SOL_PASS": "",
    "CLIENT_ID": "",
    "CLIENT_SECRET": "",
    "TOKEN_URL": "https://api-seguridad.sunat.gob.pe/v1/clientessol/{client_id}/oauth2/token/",
    "SCOPE": "https://api-sire.sunat.gob.pe",
    "BASE": "https://api-sire.sunat.gob.pe/v1/contribuyente/migeigv/libros",
    "COD_LIBRO_RVIE": "140000",
    "COD_LIBRO_RCE": "080000",
}
MEDIA_SUNAT_DIR = BASE_DIR / "media" / "sunat_raw"   # raw ZIPs and TXTs on local disk

# Archivos subidos (contratos firmados, etc.). No se sirven por URL pública:
# cada descarga pasa por un endpoint con permisos de la empresa.
MEDIA_ROOT = BASE_DIR / "media"


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-sy9#jkkf+we(5(cq-*ags%i_2x1f)0y94l0p@z(+h-yw$-ow%p",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

# La batería de tests corre con DEBUG=False, así que DEBUG no sirve para
# distinguir «producción» de «tests». Las comprobaciones de arranque
# (core/checks.py) usan esta bandera para no bloquear la suite por no tener
# configurados los secretos reales.
RUNNING_TESTS = "test" in sys.argv[:2] or bool(os.getenv("PYTEST_CURRENT_TEST"))

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")

# Orígenes del frontend autorizados a consumir el API desde el navegador.
CORS_ALLOWED_ORIGINS = env_list(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://localhost:3001,"
    "http://127.0.0.1:3000,http://127.0.0.1:3001",
)

# El frontend entra con JWT, pero SessionAuthentication sigue activa para el
# admin: si el navegador trae una cookie de sesión (p. ej. por haber entrado
# al admin), DRF exige CSRF también en el login del API, y sin esta lista el
# chequeo de Origin rechaza al frontend aunque CORS lo permita.
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'django_celery_beat',
    'django_celery_results',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'core',
    'accounts',
    'sync',
    'sunat_mailbox',
    'suppliers',
    'remype',
    'ruc_profile',
    'sunafil',
    'compliance_profile',
    'sensor_sunat',
    'sunat_itf',
    'sunat_cpe',
    'sunat_rhe',
    'sunat_intel',
    'finance_analytics',
    'afpnet',
    'colaboradores',
    'payroll',
    'financials',
    'leads',
    'billing',
    'reconciliation',
    'obligations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CorsMiddleware debe ir antes de CommonMiddleware para responder preflights.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'salud_empresarial'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
    }
}


AUTH_USER_MODEL = "accounts.User"

# URL pública del frontend: los correos de verificación y recuperación apuntan ahí.
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3001").rstrip("/")

EMAIL_BACKEND = os.getenv(
    "DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "EMPRESARIO <no-reply@empresario.pe>")
# A quién avisar cuando alguien deja sus datos en la landing. Vacío: no se avisa.
LEADS_NOTIFY_EMAIL = os.getenv("LEADS_NOTIFY_EMAIL", "")

# Suscripciones y pagos (ver billing/). La URL pública del API es la que
# Mercado Pago usa para avisar del pago; en local, la del túnel.
# Vacía: se deduce del origen desde el que se inició el pago (el túnel, el
# dominio del front), que con el proxy de Next también sirve el API.
API_PUBLIC_URL = os.getenv("API_PUBLIC_URL", "").rstrip("/")
BILLING_TRIAL_DAYS = int(os.getenv("BILLING_TRIAL_DAYS", "7"))
MERCADOPAGO_ACCESS_TOKEN = os.getenv("MERCADOPAGO_ACCESS_TOKEN", "")
# mercadopago · manual (pendiente + correo) · fake (aprueba al instante; solo
# DEBUG y solo si se pide EXPLÍCITAMENTE). Sin token y sin pedir nada, no hay
# pasarela: el checkout se rechaza. Antes DEBUG activaba `fake` solo, y un
# clic en «Continuar» activaba el plan y mandaba correos sin que nadie
# hubiera configurado cobros.
BILLING_GATEWAY = os.getenv(
    "BILLING_GATEWAY", "mercadopago" if MERCADOPAGO_ACCESS_TOKEN else "",
)
BILLING_NOTIFY_EMAIL = os.getenv("BILLING_NOTIFY_EMAIL", "")
MERCADOPAGO_WEBHOOK_SECRET = os.getenv("MERCADOPAGO_WEBHOOK_SECRET", "")
# Solo para probar con un VENDEDOR de prueba: correo del COMPRADOR de prueba que
# pagará. Mercado Pago exige que pagador y cobrador sean los dos reales o los dos
# de prueba, así que el correo del usuario real no sirve ahí.
MERCADOPAGO_TEST_PAYER_EMAIL = os.getenv("MERCADOPAGO_TEST_PAYER_EMAIL", "")
REFERRAL_TARGET = int(os.getenv("REFERRAL_TARGET", "5"))
REFERRAL_REWARD_DAYS = int(os.getenv("REFERRAL_REWARD_DAYS", "30"))

# Empresas por cuenta. Cada plan incluye una base de asientos de empresa; el
# titular puede tener asientos adicionales, que otorga el dueño del sistema
# desde el admin. El precio por asiento extra es informativo para el front.
BILLING_DEFAULT_COMPANY_SEATS = int(os.getenv("BILLING_DEFAULT_COMPANY_SEATS", "3"))
BILLING_DEFAULT_MEMBER_SEATS = int(os.getenv("BILLING_DEFAULT_MEMBER_SEATS", "3"))
BILLING_EXTRA_COMPANY_PRICE = os.getenv("BILLING_EXTRA_COMPANY_PRICE", "9")

# Sincronización manual: cuántas «Traer comprobantes» a pedido puede hacer una
# empresa por día sin costo, y el precio de cada una adicional. El límite se
# puede subir por empresa desde el admin (Organization.manual_sync_daily_limit).
SYNC_MANUAL_DAILY_LIMIT = int(os.getenv("SYNC_MANUAL_DAILY_LIMIT", "2"))
SYNC_EXTRA_MANUAL_PRICE = os.getenv("SYNC_EXTRA_MANUAL_PRICE", "5")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# En español: los mensajes de validación de Django y DRF llegan tal cual a la
# pantalla del usuario.
LANGUAGE_CODE = 'es'

TIME_ZONE = os.getenv('DJANGO_TIME_ZONE', 'America/Lima')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': int(os.getenv('API_PAGE_SIZE', '25')),
    # El bearer es la vía de acceso del frontend; la sesión queda para el
    # admin y el API navegable.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    # Cerrado también en DEBUG: antes todo el API era público con DEBUG=True,
    # y en un servicio multiempresa eso es una fuga, no una comodidad.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Techo general. Los endpoints sensibles (login, registro, recuperación)
    # llevan además su propio límite, mucho más estrecho; ver accounts.throttles.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('THROTTLE_ANON', '60/hour'),
        # En desarrollo se recarga y se prueba mucho; el techo normal (2000/h)
        # se agota y el 429 en /api/me/ tumbaba la sesión. Mucho más alto en
        # DEBUG; en producción se mantiene ajustado.
        'user': os.getenv('THROTTLE_USER', '20000/hour' if DEBUG else '2000/hour'),
        # Contra una cuenta concreta, sin importar desde cuántas IP se
        # intente: es lo que frena un ataque distribuido a un solo correo.
        'login_por_cuenta': os.getenv('THROTTLE_LOGIN_ACCOUNT', '10/hour'),
        'login_por_ip': os.getenv('THROTTLE_LOGIN_IP', '30/hour'),
        'registro': os.getenv('THROTTLE_REGISTER', '10/hour'),
        # Cada solicitud manda un correo: el límite protege la cuota y la
        # reputación del dominio, no solo la cuenta.
        'correo': os.getenv('THROTTLE_EMAIL', '5/hour'),
        'sunat_conexion': os.getenv('THROTTLE_SUNAT', '10/hour'),
        # Cada apertura del portal SOL con sesión entrega la clave al navegador.
        'sunat_portal': os.getenv('THROTTLE_SUNAT_PORTAL', '30/hour'),
        # Formulario público de la landing: por IP.
        'leads': os.getenv('THROTTLE_LEADS', '10/hour'),
    },
    'DEFAULT_RENDERER_CLASSES': (
        ('rest_framework.renderers.JSONRenderer',
         'rest_framework.renderers.BrowsableAPIRenderer') if DEBUG
        else ('rest_framework.renderers.JSONRenderer',)
    ),
}


# Caché compartida
# Debe ser compartida entre procesos: los límites de peticiones y el caché del
# panel se reparten entre todos los workers. Con la caché en memoria de Django
# (la de por defecto) cada proceso lleva su propia cuenta, así que un límite de
# 20/hora se convierte en 20 × nº de workers.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        # Base distinta a la del broker: vaciar el caché no debe tocar la cola.
        "LOCATION": os.getenv("CACHE_URL", "redis://localhost:6379/1"),
        "KEY_PREFIX": "empresario",
        "TIMEOUT": 300,
    }
}

if RUNNING_TESTS:
    # La suite no debería necesitar Redis levantado, y cada test arranca con
    # el caché limpio (ver core.testing.TenantAPITestCase).
    CACHES["default"] = {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "tests",
    }


# Celery
# https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'          # results are browsable in the admin
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Redelivered on worker loss rather than acknowledged up front: these tasks are
# idempotent (one row per supplier per day, messages upserted), so re-running is safe.
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Las sincronizaciones abren un navegador real (200-400 MB cada una) y hablan
# con SUNAT, que admite una sesión por usuario SOL. Van a su propia cola para
# poder limitarlas sin frenar el resto de tareas:
#
#   celery -A config worker -Q default -c 8
#   celery -A config worker -Q scraping -c ${SYNC_CONCURRENCY:-4}
#
# La concurrencia de esa segunda cola es el único límite real de cuántas
# empresas se sincronizan a la vez. Ver sync/tasks.py para el cálculo.
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_ROUTES = {
    'sync.run_job': {'queue': 'scraping'},
}
CELERY_TASK_TIME_LIMIT = 60 * 35
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 30
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_EXPIRES = 60 * 60 * 24 * 30     # keep a month of task history

# Run tasks inline when there is no broker, so tests and one-off scripts work.
CELERY_TASK_ALWAYS_EAGER = env_bool('CELERY_TASK_ALWAYS_EAGER', False)
# Bajo el runner de tests el correo se entrega en línea (core/emails.py): los
# tests miran el outbox y no hay broker. No se fuerza eager global porque los
# tests de sync sí cuentan con que sus tareas queden encoladas.
TESTING = "test" in sys.argv
CELERY_TASK_EAGER_PROPAGATES = True


# Logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '{asctime} {levelname} {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'root': {'handlers': ['console'], 'level': 'WARNING'},
    'loggers': {
        app: {
            'handlers': ['console'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        }
        for app in (
            'sunat_mailbox', 'suppliers', 'remype', 'ruc_profile', 'sunafil',
            'compliance_profile', 'sunat_itf', 'sunat_cpe', 'sunat_rhe',
        )
    },
}


# JSON Web Tokens
# https://django-rest-framework-simplejwt.readthedocs.io/

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("JWT_ACCESS_MINUTES", "30"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("JWT_REFRESH_DAYS", "14"))
    ),
    # Al refrescar se emite un refresh nuevo y el anterior queda en la lista
    # negra: un refresh robado sirve hasta el siguiente uso legítimo, no dos
    # semanas.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "SIGNING_KEY": os.getenv("JWT_SIGNING_KEY", SECRET_KEY),
}

# El frontend manda la empresa activa en esta cabecera cuando el usuario tiene
# acceso a más de una.
CORS_ALLOW_HEADERS = [
    "accept", "authorization", "content-type", "origin", "user-agent",
    "x-csrftoken", "x-requested-with", "x-organization",
]

# `Retry-After` no está en la lista blanca de CORS: sin exponerla, el frontend
# —que corre en otro origen— no puede leerla y solo podría decir «espera unos
# minutos» cuando el límite de peticiones salta. Con esto dice cuántos.
CORS_EXPOSE_HEADERS = ["Retry-After"]
