# Generated by Django 6.0.7 on 2026-08-17 16:36

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0006_colaborador_expense_classification'),
        ('payroll', '0002_seed_master_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxprojection',
            name='computation_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='incometaxwithholdingschedule',
            name='overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incometaxwithholdingschedule',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_tax_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incometaxwithholdingschedule',
            name='override_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='retención ajustada'),
        ),
        migrations.AddField(
            model_name='incometaxwithholdingschedule',
            name='override_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='motivo del ajuste'),
        ),
        migrations.CreateModel(
            name='IncomeTaxMonthlyInput',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(verbose_name='ejercicio')),
                ('month', models.PositiveSmallIntegerField(verbose_name='mes')),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ingreso afecto real')),
                ('withheld', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='retención practicada')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='nota')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_monthly_inputs', to='colaboradores.colaborador')),
            ],
            options={
                'verbose_name': 'histórico mensual de renta',
                'verbose_name_plural': 'históricos mensuales de renta',
                'ordering': ['year', 'month'],
                'constraints': [models.UniqueConstraint(fields=('colaborador', 'year', 'month'), name='unique_monthly_input')],
            },
        ),
    ]
