# Generated by Django 6.0.7 on 2026-08-05 14:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItfRecord',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, help_text='RUC whose ITF is being consulted (form field numdocdec).', max_length=11, verbose_name='RUC contribuyente')),
                ('section', models.CharField(choices=[('accumulated', 'Movimientos Acumulados'), ('error_reversal', 'Movimientos de Contra Asientos por Error'), ('exemption', 'Exoneración, Convenios e Inafectación')], db_index=True, max_length=20)),
                ('period', models.CharField(db_index=True, help_text='Tax period yyyymm (Período).', max_length=6)),
                ('declarant_ruc', models.CharField(blank=True, help_text='RUC of the bank/declarant.', max_length=11)),
                ('declarant_name', models.CharField(blank=True, max_length=200)),
                ('doc_type', models.CharField(blank=True, help_text='Tipo Doc.', max_length=2)),
                ('kind', models.CharField(blank=True, help_text='Tipo (e.g. Afecta).', max_length=40)),
                ('movement', models.CharField(blank=True, help_text='Movimiento (e.g. Usando cuenta).', max_length=60)),
                ('modality', models.CharField(blank=True, help_text='Modalidad.', max_length=60)),
                ('operation_code', models.CharField(blank=True, help_text='Cod. Oper.', max_length=6)),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Base.', max_digits=16, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, help_text='Impuesto.', max_digits=16, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('raw', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-period', 'declarant_ruc', 'operation_code'],
                'indexes': [models.Index(fields=['taxpayer_id', 'section', 'period'], name='sunat_itf_i_taxpaye_44304a_idx'), models.Index(fields=['-period'], name='sunat_itf_i_period_566421_idx')],
            },
        ),
    ]
