# Generated by Django 6.0.7 on 2026-08-01 04:04

import core.models
import django.db.models.deletion
import suppliers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RucSnapshot',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(db_index=True, max_length=11, validators=[suppliers.validators.validate_ruc], verbose_name='RUC')),
                ('captured_on', models.DateField(db_index=True)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('taxpayer_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, db_index=True, max_length=60)),
                ('condition', models.CharField(blank=True, db_index=True, max_length=60)),
                ('fiscal_address', models.TextField(blank=True)),
                ('economic_activities', models.TextField(blank=True)),
                ('electronic_invoicing', models.TextField(blank=True)),
                ('registries', models.TextField(blank=True)),
                ('registered_on', models.DateField(blank=True, null=True)),
                ('started_activities_on', models.DateField(blank=True, null=True)),
                ('has_coactive_debt', models.BooleanField(db_index=True, default=False)),
                ('has_tax_omissions', models.BooleanField(db_index=True, default=False)),
                ('has_probatory_acts', models.BooleanField(db_index=True, default=False)),
                ('reactiva_peru_debt', models.BooleanField(default=False, help_text='Coactive debt over 1 UIT under Reactiva Perú.')),
                ('covid_guarantee_debt', models.BooleanField(default=False, help_text='Coactive debt over 1 UIT under the COVID-19 programme.')),
                ('has_risk_signals', models.BooleanField(db_index=True, default=False, help_text='Any of the risk sections returned data.')),
                ('worker_count', models.PositiveIntegerField(blank=True, help_text='Workers declared in the most recent period.', null=True)),
                ('latest_worker_period', models.CharField(blank=True, max_length=7)),
                ('changed', models.BooleanField(db_index=True, default=False, help_text='Status, condition or risk signals differ from the previous snapshot.')),
                ('change_summary', models.TextField(blank=True)),
                ('succeeded', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-captured_on', 'ruc'],
                'indexes': [models.Index(fields=['ruc', '-captured_on'], name='ruc_profile_ruc_ea6dd5_idx')],
                'constraints': [models.UniqueConstraint(fields=('ruc', 'captured_on'), name='unique_ruc_snapshot_per_day')],
            },
        ),
        migrations.CreateModel(
            name='LegalRepresentative',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(blank=True, max_length=40)),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('since', models.CharField(blank=True, max_length=20)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_representatives', to='ruc_profile.rucsnapshot')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='RucSection',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('title', models.TextField(blank=True)),
                ('has_data', models.BooleanField(default=False)),
                ('answer', models.BooleanField(blank=True, help_text='Yes/no sections only.', null=True)),
                ('tables', models.JSONField(blank=True, default=list, help_text='[{headers: [...], rows: [[...]]}]')),
                ('text', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ruc_profile.rucsnapshot')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'key'), name='unique_section_per_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='WorkerHeadcount',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7)),
                ('workers', models.PositiveIntegerField(blank=True, null=True)),
                ('pensioners', models.PositiveIntegerField(blank=True, null=True)),
                ('service_providers', models.PositiveIntegerField(blank=True, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headcounts', to='ruc_profile.rucsnapshot')),
            ],
            options={
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'period'), name='unique_headcount_per_period')],
            },
        ),
    ]
