# Generated by Django 6.0.7 on 2026-08-23 19:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruc_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RucTaxAffectation',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(db_index=True, max_length=11, verbose_name='RUC')),
                ('tributo', models.CharField(max_length=120)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('afecto_desde', models.DateField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'tributo afecto',
                'verbose_name_plural': 'tributos afectos',
                'ordering': ['ruc', 'tributo'],
            },
        ),
    ]
