# Generated by Django 6.0.7 on 2026-08-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruc_profile', '0002_regimen_sunat'),
    ]

    operations = [
        migrations.AddField(
            model_name='rucsnapshot',
            name='branch_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
