# Generated by Django 6.0.7 on 2026-08-11 18:02

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_tax_regime_calendar_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfpnetAffiliate',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, max_length=11, verbose_name='RUC')),
                ('cuspp', models.CharField(db_index=True, max_length=20, verbose_name='CUSPP')),
                ('document_type', models.CharField(blank=True, max_length=20)),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('afp', models.CharField(choices=[('habitat', 'AFP Habitat'), ('integra', 'AFP Integra'), ('prima', 'Prima AFP'), ('profuturo', 'Profuturo AFP'), ('desconocida', 'Sin identificar')], default='desconocida', max_length=12)),
                ('commission_type', models.CharField(blank=True, max_length=30)),
                ('affiliated_on', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['full_name', 'cuspp'],
                'constraints': [models.UniqueConstraint(fields=('taxpayer_id', 'cuspp'), name='unique_afpnet_affiliate')],
            },
        ),
        migrations.CreateModel(
            name='AfpnetDebt',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, max_length=11, verbose_name='RUC')),
                ('period', models.CharField(db_index=True, max_length=6, verbose_name='período')),
                ('afp', models.CharField(choices=[('habitat', 'AFP Habitat'), ('integra', 'AFP Integra'), ('prima', 'Prima AFP'), ('profuturo', 'Profuturo AFP'), ('desconocida', 'Sin identificar')], default='desconocida', max_length=12)),
                ('concept', models.CharField(blank=True, max_length=120)),
                ('principal', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-period', 'afp'],
                'indexes': [models.Index(fields=['taxpayer_id', 'period'], name='afpnet_afpn_taxpaye_265293_idx')],
                'constraints': [models.UniqueConstraint(fields=('taxpayer_id', 'period', 'afp', 'concept'), name='unique_afpnet_debt')],
            },
        ),
        migrations.CreateModel(
            name='AfpnetDeclaration',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, max_length=11, verbose_name='RUC')),
                ('period', models.CharField(db_index=True, help_text='YYYYMM', max_length=6, verbose_name='período')),
                ('afp', models.CharField(choices=[('habitat', 'AFP Habitat'), ('integra', 'AFP Integra'), ('prima', 'Prima AFP'), ('profuturo', 'Profuturo AFP'), ('desconocida', 'Sin identificar')], default='desconocida', max_length=12)),
                ('presentation_number', models.CharField(blank=True, max_length=40)),
                ('presented_at', models.DateField(blank=True, null=True)),
                ('affiliate_count', models.PositiveIntegerField(default=0)),
                ('remuneration_total', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('contribution_total', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('is_paid', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='La fila tal como vino, para auditar el parseo.')),
            ],
            options={
                'ordering': ['-period', 'afp'],
                'indexes': [models.Index(fields=['taxpayer_id', 'period'], name='afpnet_afpn_taxpaye_579eff_idx')],
                'constraints': [models.UniqueConstraint(fields=('taxpayer_id', 'period', 'afp', 'presentation_number'), name='unique_afpnet_declaration')],
            },
        ),
        migrations.CreateModel(
            name='AfpnetDocument',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, max_length=11, verbose_name='RUC')),
                ('kind', models.CharField(choices=[('constancia_presentacion', 'Constancia de presentación'), ('constancia_pago', 'Constancia de pago'), ('ticket', 'Ticket de pago'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('period', models.CharField(blank=True, db_index=True, max_length=6)),
                ('afp', models.CharField(choices=[('habitat', 'AFP Habitat'), ('integra', 'AFP Integra'), ('prima', 'Prima AFP'), ('profuturo', 'Profuturo AFP'), ('desconocida', 'Sin identificar')], default='desconocida', max_length=12)),
                ('number', models.CharField(blank=True, max_length=60)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='afpnet/%Y/%m/')),
                ('checksum', models.CharField(blank=True, db_index=True, help_text='SHA-256 del archivo: evita volver a bajar lo que ya está.', max_length=64)),
                ('source_url', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-issued_on', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('taxpayer_id', 'kind', 'period', 'afp', 'number'), name='unique_afpnet_document')],
            },
        ),
        migrations.CreateModel(
            name='AfpnetSession',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, max_length=11, verbose_name='RUC')),
                ('username', models.CharField(blank=True, max_length=60)),
                ('encrypted_cookies', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('caducada', 'Caducada'), ('invalida', 'Credenciales rechazadas')], default='caducada', max_length=10)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='afpnet_session', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'sesión AFPnet',
                'verbose_name_plural': 'sesiones AFPnet',
                'ordering': ['taxpayer_id'],
            },
        ),
    ]
