# Generated by Django 6.0.7 on 2026-08-12 14:44

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_tax_regime_calendar_token'),
        ('afpnet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afpnetdeclaration',
            name='affiliate_count',
        ),
        migrations.RemoveField(
            model_name='afpnetdeclaration',
            name='contribution_total',
        ),
        migrations.RemoveField(
            model_name='afpnetdeclaration',
            name='remuneration_total',
        ),
        migrations.AddField(
            model_name='afpnetdeclaration',
            name='bank',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='afpnetdeclaration',
            name='nominal_fondo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='afpnetdeclaration',
            name='nominal_ryr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='afpnetdeclaration',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afpnetdeclaration',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='afpnetdeclaration',
            name='ticket',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='afpnetdeclaration',
            name='worker_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='AfpnetCompany',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, max_length=11, verbose_name='RUC')),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=80)),
                ('province', models.CharField(blank=True, max_length=80)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('representative', models.CharField(blank=True, max_length=255)),
                ('representative_document', models.CharField(blank=True, max_length=20)),
                ('representative_role', models.CharField(blank=True, max_length=120)),
                ('representative_email', models.EmailField(blank=True, max_length=254)),
                ('representative_phone', models.CharField(blank=True, max_length=40)),
                ('second_signature', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='afpnet_company', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'empresa en AFPnet',
                'verbose_name_plural': 'empresas en AFPnet',
            },
        ),
        migrations.CreateModel(
            name='AfpnetPeriodSummary',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, max_length=11, verbose_name='RUC')),
                ('period', models.CharField(db_index=True, max_length=6, verbose_name='período')),
                ('total_op', models.PositiveIntegerField(default=0)),
                ('op_cierta', models.PositiveIntegerField(default=0)),
                ('op_presunta', models.PositiveIntegerField(default=0)),
                ('op_con_deuda', models.PositiveIntegerField(default=0)),
                ('op_sin_deuda', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('taxpayer_id', 'period'), name='unique_afpnet_period_summary')],
            },
        ),
    ]
