# Generated by Django 6.0.7 on 2026-08-12 14:58

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afpnet', '0002_remove_afpnetdeclaration_affiliate_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfpnetContribution',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, max_length=11, verbose_name='RUC')),
                ('period', models.CharField(db_index=True, max_length=6, verbose_name='período')),
                ('obligation_id', models.CharField(blank=True, max_length=40)),
                ('kind', models.CharField(blank=True, max_length=2)),
                ('has_employment', models.BooleanField(default=True)),
                ('remuneration', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('obliged_fund', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('obliged_insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('obliged_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('declared_fund', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('paid_fund', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('declared_unpaid', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='afpnet.afpnetaffiliate')),
            ],
            options={
                'ordering': ['-period'],
                'indexes': [models.Index(fields=['taxpayer_id', 'period'], name='afpnet_afpn_taxpaye_a1ec27_idx')],
                'constraints': [models.UniqueConstraint(fields=('affiliate', 'period'), name='unique_afpnet_contribution')],
            },
        ),
    ]
