# Generated by Django 6.0.7 on 2026-08-04 18:14

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRating',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, help_text='Taxpayer identification number the rating belongs to.', max_length=11, verbose_name='RUC')),
                ('period', models.PositiveIntegerField(help_text="Calification quarter, SUNAT's trimCal (e.g. 202602).")),
                ('execution_period', models.PositiveIntegerField(blank=True, help_text="Month the calification was computed, SUNAT's perEjec.", null=True)),
                ('preliminary_category', models.CharField(blank=True, help_text="SUNAT's codCatPrel.", max_length=2)),
                ('rating', models.CharField(blank=True, choices=[('A', 'Nivel de cumplimiento muy alto'), ('B', 'Nivel de cumplimiento alto'), ('C', 'Nivel de cumplimiento medio'), ('D', 'Nivel de cumplimiento bajo'), ('E', 'Nivel de cumplimiento muy bajo')], help_text="Final calificación, SUNAT's codVarFinal (A best to E worst).", max_length=2)),
                ('evaluation_start', models.PositiveIntegerField(blank=True, help_text="First evaluated month, SUNAT's perEvalIni.", null=True)),
                ('evaluation_end', models.PositiveIntegerField(blank=True, help_text="Last evaluated month, SUNAT's perEvalFin.", null=True)),
                ('data_location_code', models.SmallIntegerField(blank=True, help_text="SUNAT's codUbicaDatos, stored verbatim; semantics undocumented.", null=True)),
                ('loaded_at', models.DateTimeField(blank=True, help_text='When SUNAT loaded the data (fecCarga).', null=True)),
                ('is_current', models.BooleanField(default=False, help_text="True for the quarter SUNAT's cabecera endpoint reports as vigente.")),
                ('header_payload', models.JSONField(blank=True, default=dict)),
                ('detail_payload', models.JSONField(blank=True, null=True)),
                ('detail_fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-period'],
                'indexes': [models.Index(fields=['taxpayer_id', 'is_current'], name='compliance__taxpaye_243d79_idx')],
                'constraints': [models.UniqueConstraint(fields=('taxpayer_id', 'period'), name='unique_rating_per_taxpayer_period')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceVariable',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variable_type', models.CharField(choices=[('P', 'Ponderación'), ('V', 'Vinculación'), ('D', 'Calificación directa')], db_index=True, max_length=2)),
                ('type_label', models.CharField(blank=True, help_text="SUNAT's desTipoVariable.", max_length=60)),
                ('code', models.CharField(blank=True, help_text="SUNAT's codVariable (e.g. v0615).", max_length=20)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, help_text="SUNAT's desGravedad: Leve, Grave or Muy grave.", max_length=30)),
                ('entity_name', models.CharField(blank=True, help_text="SUNAT's nomEntidad backing table.", max_length=80)),
                ('is_complete', models.BooleanField(default=True, help_text="SUNAT's indCompletado.")),
                ('is_multipage', models.BooleanField(default=False, help_text="SUNAT's indMultipagina.")),
                ('field_metadata', models.JSONField(blank=True, default=dict)),
                ('records', models.JSONField(blank=True, default=list)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('observation', models.JSONField(blank=True, help_text="SUNAT's observacion: the descargo/appeal state for this variable.", null=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='compliance_profile.compliancerating')),
            ],
            options={
                'ordering': ['variable_type', 'code', 'created_at'],
                'indexes': [models.Index(fields=['rating', 'variable_type'], name='compliance__rating__bad844_idx')],
            },
        ),
    ]
