# Generated by Django 6.0.7 on 2026-08-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliancerating',
            options={'ordering': ['-period', '-execution_period']},
        ),
        migrations.RemoveConstraint(
            model_name='compliancerating',
            name='unique_rating_per_taxpayer_period',
        ),
        migrations.AddConstraint(
            model_name='compliancerating',
            constraint=models.UniqueConstraint(fields=('taxpayer_id', 'period', 'execution_period'), name='unique_rating_per_taxpayer_period_execution'),
        ),
    ]
