# Generated by Django 6.0.7 on 2026-08-07 17:13

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sunat_cpe', '0002_cpe_daily_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAiSummary',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('period', models.CharField(db_index=True, max_length=6)),
                ('fingerprint', models.CharField(max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=60)),
                ('summary', models.TextField()),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'finance AI summaries',
                'ordering': ['-period', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAlert',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('dedup_key', models.CharField(max_length=160)),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Media'), ('info', 'Informativa')], max_length=10)),
                ('period', models.CharField(blank=True, max_length=6)),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('recommendation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('nueva', 'Nueva'), ('en_revision', 'En revisión'), ('resuelta', 'Resuelta'), ('descartada', 'Descartada')], default='nueva', max_length=15)),
            ],
            options={
                'ordering': ['-period', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('account_ruc', 'dedup_key'), name='unique_finance_alert_dedup')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceExtract',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('done', 'Done'), ('no_xml', 'No XML available'), ('failed', 'Failed')], default='done', max_length=10)),
                ('fingerprint', models.CharField(blank=True, help_text='xml_sha256 + parser version; re-parse only when it changes.', max_length=80)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('igv_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('payment_form', models.CharField(blank=True, help_text='Contado / Credito según FormaPago.', max_length=20)),
                ('installments', models.JSONField(blank=True, default=list, help_text='Cuotas: [{"amount": …, "due_date": "YYYY-MM-DD"}].')),
                ('detraction', models.JSONField(blank=True, help_text='{"percent": …, "amount": …} cuando el UBL declara detracción.', null=True)),
                ('reference_id', models.CharField(blank=True, help_text='Comprobante afectado (BillingReference).', max_length=40)),
                ('reference_reason_code', models.CharField(blank=True, max_length=4)),
                ('reference_reason', models.CharField(blank=True, help_text='Motivo (DiscrepancyResponse).', max_length=255)),
                ('items', models.JSONField(blank=True, default=list, help_text='Líneas: [{"description": …, "quantity": …, "amount": …}].')),
                ('supplier_address', models.CharField(blank=True, max_length=255)),
                ('customer_address', models.CharField(blank=True, max_length=255)),
                ('notes', models.JSONField(blank=True, default=list, help_text='cbc:Note del XML.')),
                ('error', models.TextField(blank=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extract', to='sunat_cpe.electronicinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
