# Generated by Django 6.0.7 on 2026-08-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeaisummary',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='financeaisummary',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='financeaisummary',
            name='actions',
            field=models.JSONField(blank=True, default=list, help_text='Acciones sugeridas: [{"id", "action", "owner", "due_date", "status", "why"}], hasta 3.'),
        ),
        migrations.AddField(
            model_name='financeaisummary',
            name='attention',
            field=models.JSONField(blank=True, default=list, help_text='Requieren atención: [{"title": …, "detail": …}], hasta 3.'),
        ),
        migrations.AddField(
            model_name='financeaisummary',
            name='key_changes',
            field=models.JSONField(blank=True, default=list, help_text='Cambios clave: hasta 3 frases.'),
        ),
        migrations.AlterField(
            model_name='financeaisummary',
            name='summary',
            field=models.TextField(help_text='Lectura ejecutiva, máximo 60 palabras.'),
        ),
    ]
