# Generated by Django 6.0.7 on 2026-08-15 17:43

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_analytics', '0002_briefing_blocks'),
        ('sunat_cpe', '0003_fix_html_entity_amounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceOverride',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Reemplaza al total de SUNAT cuando no es nulo.', max_digits=16, null=True)),
                ('counterparty', models.CharField(blank=True, help_text='Reemplaza a la contraparte mostrada.', max_length=200)),
                ('note', models.TextField(blank=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='override', to='sunat_cpe.electronicinvoice')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualEntry',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('direction', models.CharField(choices=[('emitida', 'Emitida'), ('recibida', 'Recibida')], db_index=True, max_length=10)),
                ('entry_date', models.DateField()),
                ('period', models.CharField(db_index=True, help_text='aaaamm, derivado de entry_date.', max_length=6)),
                ('description', models.CharField(max_length=200)),
                ('counterparty', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'manual entries',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['account_ruc', 'direction', 'period'], name='finance_ana_account_b61141_idx')],
            },
        ),
    ]
