# Generated by Django 6.0.7 on 2026-08-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_analytics', '0003_invoiceoverride_manualentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualentry',
            name='category_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
