# Generated by Django 6.0.7 on 2026-08-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_analytics', '0004_manualentry_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financealert',
            name='status',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('en_revision', 'En revisión'), ('justificada', 'Justificada'), ('corregida', 'Corregida'), ('resuelta', 'Resuelta'), ('descartada', 'Descartada')], default='nueva', max_length=15),
        ),
    ]
