# Generated by Django 6.0.7 on 2026-08-23 21:16

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_analytics', '0005_alter_financealert_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancePeriodClose',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('period', models.CharField(db_index=True, max_length=6)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('account_ruc', 'period')},
            },
        ),
        migrations.CreateModel(
            name='RentaProjection',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('year', models.PositiveSmallIntegerField()),
                ('monthly_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('monthly_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('monthly_payroll', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('account_ruc', 'year')},
            },
        ),
    ]
