# Generated by Django 6.0.7 on 2026-08-07 15:22

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sunat_mailbox', '0003_message_reviewed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, max_length=11, verbose_name='RUC')),
                ('group_key', models.CharField(help_text='Canonical reference that binds the related messages.', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('why_it_matters', models.TextField(blank=True)),
                ('risk', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Media'), ('informational', 'Informativa')], default='informational', help_text='Follows the latest communication: a conclusión can lower it.', max_length=15)),
                ('status', models.CharField(choices=[('sin_revisar', 'Sin revisar'), ('en_analisis', 'En análisis'), ('requiere_accion', 'Requiere acción'), ('delegado', 'Delegado'), ('esperando_tercero', 'Esperando tercero'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado')], default='sin_revisar', max_length=20)),
                ('requires_decision', models.BooleanField(default=False)),
                ('responsible', models.CharField(blank=True, max_length=120)),
                ('next_action', models.TextField(blank=True)),
                ('exposure_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('exposure_source', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('deadline_source', models.CharField(blank=True, max_length=255)),
                ('tribute', models.CharField(blank=True, max_length=60)),
                ('tax_period', models.CharField(blank=True, max_length=7)),
                ('confidence', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='low', max_length=10)),
                ('messages', models.ManyToManyField(blank=True, related_name='cases', to='sunat_mailbox.message')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.CharField(default='sistema', max_length=120)),
                ('kind', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sunat_intel.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAnalysis',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('fingerprint', models.CharField(blank=True, help_text='SHA-256 over message content + attachment text + methodology version + model. Reprocess only when it changes.', max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=60)),
                ('comm_type', models.CharField(blank=True, max_length=120)),
                ('priority', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Media'), ('informational', 'Informativa')], default='informational', max_length=15)),
                ('requires_action', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('why_it_matters', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('tribute', models.CharField(blank=True, max_length=60)),
                ('tax_period', models.CharField(blank=True, max_length=7)),
                ('references', models.JSONField(blank=True, default=list, help_text='Document numbers found in the evidence (resolución, orden de pago, expediente…), used to group messages into cases.')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Only stored when the amount appears verbatim in a source.', max_digits=14, null=True)),
                ('amount_source', models.CharField(blank=True, max_length=255)),
                ('legal_deadline', models.DateField(blank=True, help_text='Only stored when a legal deadline is evidenced in a source. Never derived from the mailbox expires_at.', null=True)),
                ('deadline_source', models.CharField(blank=True, max_length=255)),
                ('missing_info', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='low', max_length=10)),
                ('sources', models.JSONField(blank=True, default=list, help_text='E.g. ["asunto", "adjunto:constancia.pdf"].')),
                ('raw_response', models.JSONField(blank=True, help_text='Verbatim LLM output, kept for audit.', null=True)),
                ('error', models.TextField(blank=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='sunat_mailbox.message')),
            ],
            options={
                'verbose_name_plural': 'message analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('taxpayer_id', 'group_key'), name='unique_case_group_per_taxpayer'),
        ),
    ]
