# Generated by Django 6.0.7 on 2026-08-07 15:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat_intel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VigiaMessage',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxpayer_id', models.CharField(db_index=True, max_length=11, verbose_name='RUC')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'VIGÍA')], max_length=10)),
                ('content', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('has_sufficient_info', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
