# Generated by Django 6.0.7 on 2026-08-24 04:58

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDomain',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='descripción')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'dominio de cumplimiento',
                'verbose_name_plural': 'dominios de cumplimiento',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CompanyObligation',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('applicability_status', models.CharField(choices=[('applicable', 'Aplica'), ('not_applicable', 'No aplica'), ('unknown', 'Por determinar')], default='unknown', max_length=15)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Cumple'), ('non_compliant', 'No cumple'), ('unknown', 'Sin determinar')], default='unknown', max_length=15)),
                ('workflow_status', models.CharField(choices=[('not_started', 'Sin empezar'), ('in_progress', 'En proceso'), ('blocked', 'Bloqueada'), ('completed', 'Completada')], default='not_started', max_length=15)),
                ('verification_status', models.CharField(choices=[('verified', 'Verificada'), ('self_reported', 'Declarada por la empresa'), ('inferred', 'Inferida de tus datos'), ('unverified', 'Sin evidencia')], default='unverified', max_length=15)),
                ('severity', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('applicability_reason', models.CharField(blank=True, max_length=280)),
                ('current_assessment', models.CharField(blank=True, max_length=400)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_obligations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'obligación de la empresa',
                'verbose_name_plural': 'obligaciones de la empresa',
                'ordering': ['account_ruc', 'rule__domain__sort_order', 'rule__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAction',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=600)),
                ('status', models.CharField(choices=[('suggested', 'Sugerida'), ('in_progress', 'En curso'), ('done', 'Hecha'), ('dismissed', 'Descartada')], default='suggested', max_length=15)),
                ('priority', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company_obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='obligations.companyobligation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'acción de cumplimiento',
                'verbose_name_plural': 'acciones de cumplimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='código')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('summary', models.CharField(blank=True, max_length=280, verbose_name='resumen')),
                ('obligation_type', models.CharField(choices=[('legal', 'Obligación legal'), ('contractual', 'Obligación contractual'), ('preventive_control', 'Control preventivo'), ('recommendation', 'Recomendación')], default='legal', max_length=20)),
                ('default_severity', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=10)),
                ('frequency', models.CharField(choices=[('one_time', 'Única vez'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('annual', 'Anual'), ('event_driven', 'Por evento'), ('continuous', 'Permanente')], default='one_time', max_length=15)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('legal_reference', models.CharField(blank=True, max_length=200, verbose_name='base legal')),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True, max_length=400)),
                ('applicability', models.JSONField(blank=True, default=dict, help_text='Expresión declarativa: {"all": [{"field","operator","value"}]}. Vacío = aplica siempre.', verbose_name='condiciones de aplicabilidad')),
                ('evaluator_key', models.SlugField(blank=True, max_length=60)),
                ('required_evidence', models.JSONField(blank=True, default=list)),
                ('remediation_steps', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='obligations.compliancedomain')),
            ],
            options={
                'verbose_name': 'regla de cumplimiento',
                'verbose_name_plural': 'reglas de cumplimiento',
                'ordering': ['domain__sort_order', 'sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='companyobligation',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_obligations', to='obligations.compliancerule'),
        ),
        migrations.CreateModel(
            name='ComplianceSnapshot',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, max_length=11)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('overall_score', models.PositiveSmallIntegerField(default=0)),
                ('applicable_count', models.PositiveSmallIntegerField(default=0)),
                ('compliant_count', models.PositiveSmallIntegerField(default=0)),
                ('non_compliant_count', models.PositiveSmallIntegerField(default=0)),
                ('unverified_count', models.PositiveSmallIntegerField(default=0)),
                ('overdue_count', models.PositiveSmallIntegerField(default=0)),
                ('domain_metrics', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'foto de cumplimiento',
                'verbose_name_plural': 'fotos de cumplimiento',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['snapshot_date', 'account_ruc'], name='obligations_snapsho_a33135_idx')],
                'constraints': [models.UniqueConstraint(fields=('account_ruc', 'snapshot_date'), name='unique_snapshot_per_day')],
            },
        ),
        migrations.CreateModel(
            name='ObligationAssessment',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_version', models.PositiveIntegerField(default=1)),
                ('applicability_status', models.CharField(choices=[('applicable', 'Aplica'), ('not_applicable', 'No aplica'), ('unknown', 'Por determinar')], default='unknown', max_length=15)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Cumple'), ('non_compliant', 'No cumple'), ('unknown', 'Sin determinar')], default='unknown', max_length=15)),
                ('verification_status', models.CharField(choices=[('verified', 'Verificada'), ('self_reported', 'Declarada por la empresa'), ('inferred', 'Inferida de tus datos'), ('unverified', 'Sin evidencia')], default='unverified', max_length=15)),
                ('evaluation_source', models.CharField(choices=[('rule_engine', 'Motor de reglas'), ('evidence', 'Evidencia registrada'), ('user', 'Declarado por el usuario')], default='rule_engine', max_length=15)),
                ('reason', models.CharField(blank=True, max_length=400)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('company_obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='obligations.companyobligation')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evaluación de obligación',
                'verbose_name_plural': 'evaluaciones de obligación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObligationEvidence',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('declaration', 'Declaración'), ('receipt', 'Comprobante'), ('contract', 'Contrato'), ('registration', 'Inscripción / registro'), ('certificate', 'Constancia / certificado'), ('document', 'Documento'), ('other', 'Otro')], default='document', max_length=15)),
                ('verification_status', models.CharField(choices=[('verified', 'Verificada'), ('self_reported', 'Declarada por la empresa'), ('inferred', 'Inferida de tus datos'), ('unverified', 'Sin evidencia')], default='self_reported', max_length=15)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('reference', models.JSONField(blank=True, default=dict)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=400)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('company_obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='obligations.companyobligation')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evidencia de obligación',
                'verbose_name_plural': 'evidencias de obligación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='companyobligation',
            index=models.Index(fields=['account_ruc', 'compliance_status', 'due_date'], name='obligations_account_e6b4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='companyobligation',
            index=models.Index(fields=['account_ruc', 'workflow_status', 'owner'], name='obligations_account_5b80c0_idx'),
        ),
        migrations.AddIndex(
            model_name='companyobligation',
            index=models.Index(fields=['account_ruc', 'last_evaluated_at'], name='obligations_account_eb0d13_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyobligation',
            constraint=models.UniqueConstraint(fields=('account_ruc', 'rule'), name='unique_company_rule'),
        ),
        migrations.AddIndex(
            model_name='obligationassessment',
            index=models.Index(fields=['company_obligation', 'created_at'], name='obligations_company_f51265_idx'),
        ),
    ]
