# Generated by Django 6.0.7 on 2026-08-24 05:11

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0002_seed_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligationassessment',
            name='input_snapshot',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
