# Generated by Django 6.0.7 on 2026-08-18 15:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('id', models.UUIDField(default=core.models.default_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_ruc', models.CharField(db_index=True, help_text='La empresa que recibió el servicio (usuario del recibo).', max_length=11, verbose_name='RUC de la cuenta')),
                ('issuer_doc_type', models.CharField(blank=True, max_length=2, verbose_name='tipo doc. emisor')),
                ('issuer_doc', models.CharField(db_index=True, help_text='RUC 10… o DNI del profesional independiente.', max_length=15, verbose_name='documento del emisor')),
                ('issuer_name', models.CharField(blank=True, max_length=200, verbose_name='emisor')),
                ('series', models.CharField(blank=True, max_length=10, verbose_name='serie')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('full_number', models.CharField(blank=True, max_length=30, verbose_name='serie-número')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='fecha de emisión')),
                ('period', models.CharField(blank=True, db_index=True, help_text='aaaamm, derivado de la fecha de emisión.', max_length=6, verbose_name='periodo')),
                ('currency', models.CharField(default='PEN', max_length=3, verbose_name='moneda')),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe bruto')),
                ('income_tax_withheld', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='retención de renta (8 %)')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='neto pagado')),
                ('status', models.CharField(blank=True, max_length=60, verbose_name='estado')),
                ('is_reverted', models.BooleanField(default=False, help_text='Un recibo revertido no es gasto: se lista, no suma.', verbose_name='revertido')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'recibo por honorarios',
                'verbose_name_plural': 'recibos por honorarios',
                'ordering': ['-issue_date', '-created_at'],
                'indexes': [models.Index(fields=['account_ruc', 'period'], name='sunat_rhe_f_account_2f2e5c_idx')],
                'constraints': [models.UniqueConstraint(fields=('account_ruc', 'issuer_doc', 'series', 'number'), name='unique_fee_receipt')],
            },
        ),
    ]
