# Generated by Django 6.0.7 on 2026-08-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat_rhe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceipt',
            name='detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='detail_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
