# Generated by Django 6.0.7 on 2026-09-04 13:06

import sunat_rhe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat_rhe', '0002_feereceipt_detail_feereceipt_detail_fetched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceipt',
            name='file',
            field=models.FileField(blank=True, max_length=255, upload_to=sunat_rhe.models.receipt_file_path, verbose_name='archivo'),
        ),
    ]
